package formularios.superUsuario;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Arrays;

public class FrmSuperLobby extends javax.swing.JFrame {
    String archivo = "RegistroUsuarios.txt";
    ArrayList<String> usuarios = new ArrayList();
    ArrayList<String> datosTxt = new ArrayList();
    /**
     * Creates new form FrmSuperUsuario
     */
    public FrmSuperLobby() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        cmbApuesta.removeAllItems();
        cmbApuesta.addItem("1");
        cmbApuesta.addItem("5");
        cmbApuesta.addItem("10");
        cmbApuesta.addItem("50");
        cmbApuesta.addItem("100");
        cmbApuesta.addItem("500");
        cmbApuesta.addItem("1000");
        cmbApuesta.addItem("10000");
        cmbApuesta.addItem("100000");
        cmbApuesta.addItem("1000000");
        lblBorrar.setVisible(false);
        recargarUsuariostxt();
    }

    
    public void recargarUsuariostxt(){
        cmbUsuario.removeAllItems();
        try {
            
            BufferedReader leer = new BufferedReader(new FileReader(archivo));
            String lectura = leer.readLine();
            while(lectura != null){
                String[] separados = lectura.split(":");
                if(separados[separados.length - 1].equals("U")){
                    
                    cmbUsuario.addItem(separados[2]);
                    usuarios.add(lectura + "\n");
                }
                lectura = leer.readLine();
               
            }
            if(usuarios.isEmpty()){
                btnBorrarUsuario.setEnabled(false);
                btnSacarle.setEnabled(false);
                btnAniadirle.setEnabled(false);
                cmbUsuario.addItem("No hay usuarios");
            }else{
                btnBorrarUsuario.setEnabled(true);
                btnSacarle.setEnabled(true);
                btnAniadirle.setEnabled(true);
            }
            usuarios.clear();
            leer.close();
        } catch (Exception ex) {}
    }
    
    
    public void escribirArchivo(String dato){

            try (FileWriter escritor = new FileWriter(archivo, true)) {
                escritor.append(dato);
            }
         catch (Exception e){
            
        }
    }
    
    public void limpiarArchivo(){
        File archivo = new File("RegistroUsuarios.txt");
        try {
            FileWriter escritor = new FileWriter(archivo, false);
            escritor.write("");
            
        } catch (Exception ex) {}
        
    }
    
    public ArrayList<String> leerArchivo(){
            ArrayList<String> datos = new ArrayList();
            try {
                BufferedReader leer = new BufferedReader(new FileReader(archivo));
                String lectura = leer.readLine();
               
                while(lectura != null){
                  
                    datos.add(lectura);
                    lectura = leer.readLine();
                    

                }

                leer.close();
            return datos;
            }catch(Exception e){
                
        }   
        
        return null;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBorrar = new javax.swing.JLabel();
        lblFichas = new javax.swing.JLabel();
        btnSacarle = new javax.swing.JButton();
        cmbUsuario = new javax.swing.JComboBox<>();
        cmbApuesta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBorrarUsuario = new javax.swing.JButton();
        btnAniadirle = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBorrar.setForeground(new java.awt.Color(255, 51, 51));
        lblBorrar.setText("BORRAR");
        getContentPane().add(lblBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 202, 372, -1));

        lblFichas.setForeground(new java.awt.Color(255, 255, 255));
        lblFichas.setText("Fichas:");
        getContentPane().add(lblFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 133, -1));

        btnSacarle.setText("Sacarle");
        btnSacarle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarleActionPerformed(evt);
            }
        });
        getContentPane().add(btnSacarle, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 128, -1, -1));

        cmbUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cmbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 88, -1, -1));

        cmbApuesta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 88, 99, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fichas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        btnBorrarUsuario.setText("Borrar usuario");
        btnBorrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 128, -1, -1));

        btnAniadirle.setText("Añadirle");
        btnAniadirle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirleActionPerformed(evt);
            }
        });
        getContentPane().add(btnAniadirle, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 162, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido al menu de super usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 20, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fichas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 91, 37, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lobby.jpeg.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarleActionPerformed
        int puntos = obtenerPuntos(cmbUsuario.getSelectedItem().toString());
        int resta = puntos - Integer.parseInt(cmbApuesta.getSelectedItem().toString());
        if(resta >= 0){
            operarPuntos(resta);
            lblBorrar.setVisible(false);
        }else{
            lblBorrar.setText("no le alcanzan las fichas, tiene " + puntos);
            lblBorrar.setVisible(true);
        }
        lblFichas.setText(obtenerPuntos(cmbUsuario.getSelectedItem().toString()) + "");

    }//GEN-LAST:event_btnSacarleActionPerformed

    private void cmbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuarioActionPerformed
        try{
            lblFichas.setText(obtenerPuntos(cmbUsuario.getSelectedItem().toString()) + "");
        }catch(Exception e){}
    }//GEN-LAST:event_cmbUsuarioActionPerformed

    private void btnBorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarUsuarioActionPerformed
        datosTxt = leerArchivo();
        String usuarioBorrado = "";

        limpiarArchivo();
        for (int i=0;i<datosTxt.size();i++){

            String[] datosSep = datosTxt.get(i).split(":");

            if(!cmbUsuario.getSelectedItem().equals(datosSep[2])){
                escribirArchivo((datosTxt.get(i) + "\n").replace("[", "").replace("]","").replace(", ", ":"));
            }else{
                usuarioBorrado = datosSep[2];
                File archivoHam = new File("premioHamburguesa" + usuarioBorrado + ".pdf");
                File archivo2 = new File("PremioSorpresa" + usuarioBorrado + ".pdf");
                if(archivoHam.exists()){
                    archivoHam.delete();
                }
                if(archivo2.exists()){
                    archivo2.delete();
                }
            }

        }
        lblBorrar.setText("se borro el usuario: " + usuarioBorrado);
        lblBorrar.setVisible(true);
        recargarUsuariostxt();
    }//GEN-LAST:event_btnBorrarUsuarioActionPerformed

    private void btnAniadirleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirleActionPerformed
        int puntos = obtenerPuntos(cmbUsuario.getSelectedItem().toString());

        int suma = puntos + Integer.parseInt(cmbApuesta.getSelectedItem().toString());
        operarPuntos(suma);
        lblBorrar.setVisible(false);
        lblFichas.setText(obtenerPuntos(cmbUsuario.getSelectedItem().toString()) + "");

    }//GEN-LAST:event_btnAniadirleActionPerformed
    
    public int obtenerPuntos(String usuario){
            datosTxt = leerArchivo();
            for (int i=0;i<datosTxt.size();i++){
                String[] datosSep = datosTxt.get(i).split(":");
                if(usuario.equals(datosSep[2])  && datosSep[datosSep.length - 1].equals("U")){
                    int fichas =  Integer.parseInt(datosSep[0]);
                    return fichas;
                }
            }
            return 0;
        }
    
    
    public void operarPuntos(int numero){
            datosTxt = leerArchivo();
            limpiarArchivo();
            for (int i=0;i<datosTxt.size();i++){
                    String[] datosSep = datosTxt.get(i).split(":");
                    if(cmbUsuario.getSelectedItem().equals(datosSep[2]) && datosSep[datosSep.length - 1].equals("U")){
                            datosSep[0] = numero + "";
                            escribirArchivo((Arrays.toString(datosSep) + "\n").replace("[", "").replace("]","").replace(", ", ":"));

                        }else{
                            escribirArchivo((datosTxt.get(i) + "\n").replace("[", "").replace("]","").replace(", ", ":"));
                        }
            }

    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadirle;
    private javax.swing.JButton btnBorrarUsuario;
    private javax.swing.JButton btnSacarle;
    private javax.swing.JComboBox<String> cmbApuesta;
    private javax.swing.JComboBox<String> cmbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBorrar;
    private javax.swing.JLabel lblFichas;
    // End of variables declaration//GEN-END:variables
}
