/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios.Usuario;

import formularios.juegos.Blackjack;
import formularios.juegos.CarreraDeCaballos;
import formularios.juegos.FrmJuegodePunteria;
import formularios.juegos.TragaFichas;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import static java.lang.Integer.parseInt;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;

/**
 *
 * @author usuario
 */
public class FrmLobby extends javax.swing.JFrame {
    String archivo = "RegistroUsuarios.txt";
    ArrayList<String> datosTxt = new ArrayList();
    Blackjack ventanaBlackJack;
    CarreraDeCaballos ventanaCarrera;
    
    String linea;
    
    
    
    public FrmLobby(String lineaAnt) {
        initComponents();
        datosTxt = leerArchivo();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.linea = lineaAnt;
        String[] lineaSeparada = linea.split(":");
        lblBienvenida.setText("Bienvenido al \"K\" zino: " + lineaSeparada[4]);        
        lblPuntos.setText(lineaSeparada[0] + " fichas");
        actualizarPuntos();
        
    } 
        public void limpiarArchivo(){
        
        try {
            FileWriter escritor = new FileWriter(archivo, false);
            escritor.write("");
            
            
        } catch (Exception e) {
        }
        
    }
        
        public ArrayList<String> leerArchivo(){
            ArrayList<String> datos = new ArrayList();
            try {
                BufferedReader leer = new BufferedReader(new FileReader(archivo));
                String lectura = leer.readLine();
               
                while(lectura != null){
                  
                    datos.add(lectura);
                    lectura = leer.readLine();
                    

                }

                leer.close();
            return datos;
            }catch(Exception e){
                
        }   
        
        return null;
        }
        
        
        //VERRRRRRRRRRRRR
        
        public void actualizarPuntos(){
            
            datosTxt = leerArchivo();
            String[] lineaSeparada = linea.split(":");
            for (int i=0;i<datosTxt.size();i++){
                    String[] datosSep = datosTxt.get(i).split(":");
                    if(lineaSeparada[2].equals(datosSep[2]) && datosSep[datosSep.length - 1].equals("U")){
                        int fichas =  Integer.parseInt(datosSep[0]);
                        lblPuntos.setText(fichas + " fichas");
                        if(fichas == 2147483647){
                            lblPuntos.setText("Te pasaste el juego, ahora sos el dueño del casino");
                        }else{
                            if (fichas < 200){
                                lblAimLab.setVisible(true);
                                btnAimLab.setVisible(true);
                            } else {
                                lblAimLab.setVisible(false);
                                btnAimLab.setVisible(false);
                            }
                        }
                    }
                }
        } 
        
        
        public void escribirArchivo(String dato){
        try {
            try (FileWriter escritor = new FileWriter(archivo, true)) {
                escritor.append(dato);
            }
        } catch (Exception e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBlackJack = new javax.swing.JButton();
        btnCarrera = new javax.swing.JButton();
        btnTragaFichas = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        btnAjustes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnAimLab = new javax.swing.JButton();
        lblAimLab = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBlackJack.setText("Black Jack");
        btnBlackJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlackJackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBlackJack, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 231, -1, -1));

        btnCarrera.setText("Carrera de caballos");
        btnCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarreraActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 231, -1, -1));

        btnTragaFichas.setText("Tragafichas");
        btnTragaFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTragaFichasActionPerformed(evt);
            }
        });
        getContentPane().add(btnTragaFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 231, -1, -1));

        lblBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenida.setText("Bienvenido al \"K\" zino: ");
        getContentPane().add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 64, -1, -1));

        lblPuntos.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntos.setText("Fichas = 0");
        getContentPane().add(lblPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 17, -1, -1));

        btnAjustes.setText("Mis datos");
        btnAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjustesActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, -1, -1));

        jButton1.setText("Premio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, -1, -1));

        btnAimLab.setText("Aim Lab");
        btnAimLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAimLabActionPerformed(evt);
            }
        });
        getContentPane().add(btnAimLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 285, -1, -1));

        lblAimLab.setForeground(new java.awt.Color(102, 255, 102));
        lblAimLab.setText("¿Corto en Fichas? Este minijuego te ayudará:");
        getContentPane().add(lblAimLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 288, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lobby.jpeg.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBlackJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlackJackActionPerformed
        ventanaBlackJack = new Blackjack(linea);
        ventanaBlackJack.setVisible(true);
        
        this.dispose();
      
    }//GEN-LAST:event_btnBlackJackActionPerformed

    private void btnCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarreraActionPerformed
        ventanaCarrera = new CarreraDeCaballos(linea);
        ventanaCarrera.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btnCarreraActionPerformed

    private void btnTragaFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTragaFichasActionPerformed
        TragaFichas ventanaTragaFichas = new TragaFichas(linea);
        ventanaTragaFichas.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnTragaFichasActionPerformed

    private void btnAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustesActionPerformed
        FrmDatos ventanaAjustes = new FrmDatos(linea);
        ventanaAjustes.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnAjustesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmPremios ventanaPremios = new FrmPremios(linea);
        ventanaPremios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAimLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAimLabActionPerformed
        FrmJuegodePunteria ventanaPunteria = new FrmJuegodePunteria(linea);
        ventanaPunteria.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAimLabActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAimLab;
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnBlackJack;
    private javax.swing.JButton btnCarrera;
    private javax.swing.JButton btnTragaFichas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAimLab;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblPuntos;
    // End of variables declaration//GEN-END:variables
}
