package formularios.Usuario;

import clases.Usuario;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;

public class FrmSignUp extends javax.swing.JFrame{
    String archivo = "RegistroUsuarios.txt";
    ArrayList<String> usuarios = new  ArrayList();

    public FrmSignUp() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        lblContraseniaError.setVisible(false);
        lblError.setVisible(false);
        lblUsuarioExiste.setVisible(false);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                FrmLogin ventanaLogin = new FrmLogin();
                ventanaLogin.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtUsuario1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtContrasenia1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUsuario3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtContrasenia3 = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtContraseniaRepetir = new javax.swing.JPasswordField();
        lblError = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        lblContraseniaError = new javax.swing.JLabel();
        lblUsuarioExiste = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("Usuario");

        jLabel5.setText("Contraseña");

        jLabel8.setText("Nombre");

        jLabel9.setText("Apellido");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setText("CREAR USUARIO");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 146, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 59, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 6, 206, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Repita la Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 59, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 206, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 206, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Edad");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 59, -1));
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 206, -1));
        getContentPane().add(txtContraseniaRepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 206, -1));

        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setText("Ponga un numero por favor");
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 206, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contraseña");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        lblContraseniaError.setForeground(new java.awt.Color(255, 51, 51));
        lblContraseniaError.setText("Las contraseñas no coinciden");
        getContentPane().add(lblContraseniaError, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 170, -1));

        lblUsuarioExiste.setForeground(new java.awt.Color(255, 51, 51));
        lblUsuarioExiste.setText("El usuario ya existe, seleccione otro");
        getContentPane().add(lblUsuarioExiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 198, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 470, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
            PrintWriter salida = new PrintWriter(new FileWriter(archivo, true));
            salida.close();
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
        try{
            BufferedReader br = new BufferedReader(new FileReader(archivo));
            String linea;
                while ((linea = br.readLine()) != null) {
                    if(linea.contains(":U")){
                        String[] lineaSeparada = linea.split(":");
                        if(lineaSeparada[lineaSeparada.length - 1].equals("U")){
                            usuarios.add(lineaSeparada[2]);
                        }
                               
                    }
                }
            if(!usuarios.contains(txtUsuario.getText())){
                if(!txtNombre.getText().equals("") && !txtApellido.getText().equals("") && !txtUsuario.getText().equals("") && !txtContraseniaRepetir.getText().equals("") && !txtEdad.getText().equals("") ){
                    lblUsuarioExiste.setVisible(false);
                    lblError.setVisible(false);
                    if(txtContrasenia.getText().equals(txtContraseniaRepetir.getText())){
                        Usuario user = new Usuario(500, 0,txtNombre.getText(), txtApellido.getText(), txtUsuario.getText(), txtContraseniaRepetir.getText(), Integer.parseInt(txtEdad.getText()));
                        txtNombre.setText("");
                        txtApellido.setText("");
                        txtEdad.setText("");
                        txtContraseniaRepetir.setText("");
                        txtContrasenia.setText("");
                        txtUsuario.setText("");

                        PrintWriter salida = new PrintWriter(new FileWriter(archivo, true));
                        salida.println(user.toString() + ":U");
                        salida.close();
                        lblContraseniaError.setVisible(false);

                        this.dispose();
                        FrmLogin ventanaLogin = new FrmLogin();
                        ventanaLogin.setVisible(true);
                    
                    
                    }else{
                        lblContraseniaError.setVisible(true);
                    }
            }else{
                    lblError.setText("Termine de completar los datos por favor");
                    lblError.setVisible(true);
                }
            }else{
                lblUsuarioExiste.setVisible(true);
            }
        }catch(Exception e){
            lblError.setText("Ingrese un numero por favor");
            lblError.setVisible(true);
        }
        usuarios.clear();
        
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmLogin ventanaLogin = new FrmLogin();
        this.dispose();
        ventanaLogin.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblContraseniaError;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblUsuarioExiste;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtContrasenia1;
    private javax.swing.JTextField txtContrasenia3;
    private javax.swing.JPasswordField txtContraseniaRepetir;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuario1;
    private javax.swing.JTextField txtUsuario3;
    // End of variables declaration//GEN-END:variables
}
