package formularios.superUsuario;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;


/**
 *
 * @author usuario
 */
public class FrmSuperLogin extends javax.swing.JFrame {
    String nombreArchivo = "RegistroUsuarios.txt";
    File archivo = new File(nombreArchivo);
    
    
    
    FrmSuperLobby ventanaSuper = new FrmSuperLobby();
    /**
     * Creates new form Login
     */
    public FrmSuperLogin() {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        lblError.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        lblError = new javax.swing.JLabel();
        lblContraseniaMal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setText("jLabel2");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 84, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO AL MODO DE SUPERUSUARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 6, 259, 72));

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 188, -1, -1));

        btnSignUp.setText("SIGN UP");
        btnSignUp.setToolTipText("");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 87, 59, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 84, 206, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 127, -1, -1));

        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("¿No tienes una cuenta? Presiona aqui para crearla");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 124, 206, -1));

        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setText("Completar los datos porfavor!");
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 222, -1, -1));

        lblContraseniaMal.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblContraseniaMal, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 158, 206, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lobby.jpeg.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        FrmSuperSignUp ventanaSign = new FrmSuperSignUp();
        this.dispose();
        ventanaSign.setVisible(true);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(leerArchivo().isEmpty()){
            lblContraseniaMal.setText("No existe ese usuario");
            lblContraseniaMal.setVisible(true);
        }else{
            String usuario = txtUsuario.getText();
            String contrasenia = txtContrasenia.getText();
            if(!usuario.equals("") && !contrasenia.equals("")){
                lblError.setVisible(false);

                try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                    String linea;

                    while ((linea = br.readLine()) != null) {
                        if(linea.contains(usuario)){
                            String[] lineaSeparada = linea.split(":");
                            if(lineaSeparada[lineaSeparada.length - 1].equals("S")){
                                if(lineaSeparada[0].equals(usuario)){
                                    if(lineaSeparada[1].equals(contrasenia)){
                                        lblContraseniaMal.setVisible(false);
                                        FrmSuperLobby ventanaLobby = new FrmSuperLobby();
                                        ventanaLobby.setVisible(true);
                                        lblContraseniaMal.setText("");
                                        this.setVisible(false);
                                        break;
                                    }else{
                                        lblContraseniaMal.setText("Contraseña incorrecta");
                                        lblContraseniaMal.setVisible(true);
                                        break;
                                    }

                                }
                            }else{
                                lblContraseniaMal.setText("No existe ese usuario");
                                lblContraseniaMal.setVisible(true);
                            }
                        }
                    }
                    br.close();
                    br.close();

                } catch (IOException e) {
                    e.printStackTrace();
                }
            }else{
                lblError.setVisible(true);
                lblContraseniaMal.setVisible(false);
            }
        
        }
        
        
        
    }//GEN-LAST:event_btnLoginActionPerformed
    
    
    
    public ArrayList<String> leerArchivo(){
            ArrayList<String> datos = new ArrayList();
            try {
                BufferedReader leer = new BufferedReader(new FileReader(archivo));
                String lectura = leer.readLine();
                 while(lectura != null){
                 
                    datos.add(lectura);
                    lectura = leer.readLine();
                    
                }
             
            return datos;
            }catch(Exception e){
                
        }
        return null;
        }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblContraseniaMal;
    private javax.swing.JLabel lblError;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
